name: tekaly_sembast_synced
description: Sembast synchronized database.
version: 1.0.1
publish_to: none

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  cv: ">=1.1.0+4"
  sembast: '>=3.8.5'
  tekartik_app_cv_sembast:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_cv_sembast
    version: '>=0.5.3'
  tekartik_app_cv_firestore:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_cv_firestore
    version: '>=0.1.0'
  tekartik_firebase_firestore_rest:
    git:
      url: https://github.com/tekartik/firebase_rest.dart
      path: firestore_rest
    version: '>=0.8.0'
  tekartik_firebase_storage_rest:
    git:
      url: https://github.com/tekartik/firebase_rest.dart
      path: storage_rest
  tekartik_firebase_firestore:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore
    version: '>=0.8.0'
  tekartik_firebase_storage:
    git:
      url: https://github.com/tekartik/firebase_storage.dart
      path: storage
    version: '>=0.8.0'
  tekartik_firebase_storage_fs:
    git:
      url: https://github.com/tekartik/firebase_storage.dart
      path: storage_fs
    version: '>=0.4.0'
  tekartik_firebase_auth:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      path: auth
    version: '>=0.8.0'
  tekartik_firebase_auth_local:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      path: auth_local
    version: '>=0.3.8'
  tekartik_firebase_firestore_sembast:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore_sembast
    version: '>=0.8.0'
  tekartik_app_http:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_http
    version: '>=0.1.0'
  tekartik_firebase_auth_rest:
    git:
      url: https://github.com/tekartik/firebase_rest.dart
      path: auth_rest
    version: '>=0.3.8'
  tekartik_app_crypto:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_crypto
  tekartik_firebase_functions:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      path: firebase_functions
    version: '>=0.2.1'
  tekartik_firebase_functions_http:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      path: firebase_functions_http
    version: '>=0.2.1'
  tekartik_app_sembast:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_sembast
    version: '>=0.1.0'
  meta: ">=1.15.0"
  synchronized:
  path: ">=1.9.0"
  http:
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      path: http
  tekartik_firebase_rest:
    git:
      url: https://github.com/tekartik/firebase_rest.dart
      path: firebase_rest
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
  tekartik_firebase_local:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_local
  tekartik_app_common_utils:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app
dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
  fs_shim: ">=2.3.3+1"
resolution: workspace
