name: _
publish_to: none
environment:
  sdk: ^3.12.0
workspace:
  - flutter_packages/file_download
  - flutter_packages/file_download_flutter_example
  - flutter_packages/file_picker_flutter
  - flutter_packages/file_picker_flutter_example
  - flutter_packages/firestore_explorer
  - test/firestore_explorer_test_app
  - packages/file_download_web
  - packages/file_picker
  - packages/firestore_synced
  - packages/sembast_synced
  - packages/sembast_synced_test
  - packages/sdb_synced
  - packages/sdb_synced_test
  - packages/tekaly_assets
  - packages/tekaly_stat
  - packages/sembast_synced_rpc
  - packages/tekaly_media_cache
